const items = [
    {
        id: '001',
        image: 'images/watch1.png',
        company: 'Apple',
        item_name: 'Series 9 GPS + Cellular Watch',
        original_price: 80900,
        current_price: 77299,
        discount: 3601,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 5,
            count: 105,
        },
    },

    {
        id: '002',
        image: 'images/watch2.png',
        company: 'Armani Exchange',
        item_name: 'Men Skeletonl Automatic Watch',
        original_price: 25999,
        current_price: 23995,
        discount: 2004,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.2,
            count: 10,
        },
    },

    {
        id: '003',
        image: 'images/watch3.png',
        company: 'Emporio Armani',
        item_name: 'Leather Straps Motion Watch',
        original_price: 34999,
        current_price: 33495,
        discount: 1504,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.1,
            count: 18,
        },
    },

    {
        id: '004',
        image: 'images/watch4.png',
        company: 'Titan',
        item_name: 'Men Blue Analogue Watch',
        original_price: 18999,
        current_price: 18765,
        discount: 234,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.1,
            count: 37,
        },
    },

    {
        id: '005',
        image: 'images/watch5.png',
        company: 'Fossil',
        item_name: 'Men Analogue Automatic Watch',
        original_price: 20900,
        current_price: 19995,
        discount: 905,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.4,
            count: 51,
        },
    },

    {
        id: '006',
        image: 'images/watch1.png',
        company: 'Apple',
        item_name: 'Series 9 GPS + Cellular Watch',
        original_price: 80900,
        current_price: 77299,
        discount: '3601',
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 5,
            count: 105,
        },
    },

    {
        id: '007',
        image: 'images/watch2.png',
       company: 'Armani Exchange',
        item_name: 'Men Skeletonl Automatic Watch',
        original_price: 25999,
        current_price: 23995,
        discount: 2004,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.2,
            count: 10,
        },
    },

    {
        id: '008',
        image: 'images/watch3.png',
       company: 'Emporio Armani',
        item_name: 'Leather Straps Motion Watch',
        original_price: 34999,
        current_price: 33495,
        discount: 1504,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.1,
            count: 18,
        },
    },

    {
        id: '009',
        image: 'images/watch4.png',
        company: 'Titan',
        item_name: 'Men Blue Analogue Watch',
        original_price: 18999,
        current_price: 18765,
        discount: 234,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.1,
            count: 37,
        },
    },

    {
        id: '010',
        image: 'images/watch5.png',
        company: 'Fossil',
        item_name: 'Men Analogue Automatic Watch',
        original_price: 20900,
        current_price: 19995,
        discount: 905,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.4,
            count: 51,
        },
    },
];